apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: nodejs-express-app
spec:
  # Add fields here
  version: 1.0.0
  applicationImage: nodejs-express-app
  stack: nodejs-express
  service:
    type: NodePort
    port: 3000
    annotations:
      prometheus.io/scrape: "true"
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 5
    periodSeconds: 2
  expose: true
